wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.1
    start_time: 1681298759.55126
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 19
      - 23
      4: 3.10.1
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 1000
